const natural = require('natural')

const classifierAction = new natural.LogisticRegressionClassifier()
// const classifierObject = new natural.BayesClassifier()

// Light/Switch Turn On Classifiers
classifierAction.addDocument('light_on', 'light_on')
classifierAction.addDocument('light on', 'light_on')
classifierAction.addDocument('turn the lights on', 'light_on')
classifierAction.addDocument('it is too dark', 'light_on')
classifierAction.addDocument('turn on the lights', 'light_on')
classifierAction.addDocument('lights should be on', 'light_on')
classifierAction.addDocument('activate lights', 'light_on')
classifierAction.addDocument('activate switch', 'switch_on')
classifierAction.addDocument('turn switch on', 'switch_on')
classifierAction.addDocument('put on lights', 'light_on')
classifierAction.addDocument('start up lights', 'light_on')
classifierAction.addDocument('put on lights', 'light_on')
classifierAction.addDocument('initiate lights', 'light_on')
classifierAction.addDocument('trigger lights on', 'light_on')
classifierAction.addDocument('start lights', 'light_on')
classifierAction.addDocument('turn on switch', 'switch_on')
classifierAction.addDocument('activate switch', 'switch_on')
classifierAction.addDocument('the lights should be on', 'light_on')
classifierAction.addDocument("it's dark in here", 'light_on')
classifierAction.addDocument('its dark in here', 'light_on')
classifierAction.addDocument('switch that thing on', 'switch_on')
classifierAction.addDocument('bring up the lights', 'light_on')
classifierAction.addDocument('let there be light', 'light_on')

// classifierAction.addDocument('turn on camera', 'turn_on')

// Light/Switch Turn Off Classifiers
classifierAction.addDocument('light_off', 'light_off')
classifierAction.addDocument('light off', 'light_off')
classifierAction.addDocument('turn the lights off', 'light_off')
classifierAction.addDocument('kill the lights', 'light_off')
classifierAction.addDocument('turn off light', 'light_off')
classifierAction.addDocument('switch off', 'switch_off')
classifierAction.addDocument('it is too bright in here', 'light_off')
classifierAction.addDocument('why is the fan on?', 'switch_off')
classifierAction.addDocument('why are the the lights on?', 'light_off')
classifierAction.addDocument('why are the lights still on?', 'light_off')
classifierAction.addDocument('cut the lights', 'light_off')
classifierAction.addDocument('the lights should be off', 'light_off')
classifierAction.addDocument('deactivate lights', 'light_off')
classifierAction.addDocument('deactivate switch', 'switch_off')
classifierAction.addDocument('turn off lights', 'light_off')
classifierAction.addDocument('turn off switch', 'switch_off')
classifierAction.addDocument('shut down lights', 'light_off')
classifierAction.addDocument('bring down the lights', 'light_off')
classifierAction.addDocument('dark', 'light_off')
classifierAction.addDocument('off', 'switch_off')


// Volume Up Classifiers
classifierAction.addDocument('volume_up', 'volume_up')
classifierAction.addDocument('volume up', 'volume_up')
classifierAction.addDocument('turn it up', 'volume_up')
classifierAction.addDocument('turn that up', 'volume_up')
classifierAction.addDocument('make it louder', 'volume_up')
classifierAction.addDocument('too quiet', 'volume_up')
classifierAction.addDocument('raise volume', 'volume_up')
classifierAction.addDocument('raise level', 'volume_up')
classifierAction.addDocument('raise sound', 'volume_up')
classifierAction.addDocument('sound up', 'volume_up')
classifierAction.addDocument('up', 'volume_up')
classifierAction.addDocument('raise', 'volume_up')


// Volume Down Classifiers
classifierAction.addDocument('volume_down', 'volume_down')
classifierAction.addDocument('volume down', 'volume_down')
classifierAction.addDocument('turn it down', 'volume_down')
classifierAction.addDocument('turn that down', 'volume_down')
classifierAction.addDocument('too loud', 'volume_down')
classifierAction.addDocument('make it quieter', 'volume_down')
classifierAction.addDocument('lower volume', 'volume_down')
classifierAction.addDocument('lower level', 'volume_down')
classifierAction.addDocument('lower sound', 'volume_down')
classifierAction.addDocument('sound down', 'volume_down')
classifierAction.addDocument('down', 'volume_down')
classifierAction.addDocument('lower', 'volume_down')

// Mute Classifiers
classifierAction.addDocument('volume_mute', 'volume_mute')
classifierAction.addDocument('volume mute', 'volume_mute')
classifierAction.addDocument('turn off volume', 'volume_mute')
classifierAction.addDocument('total silence', 'volume_mute')
classifierAction.addDocument('mute device', 'volume_mute')
classifierAction.addDocument('turn volume off', 'volume_mute')
classifierAction.addDocument('mute', 'volume_mute')
classifierAction.addDocument('stop all noise', 'volume_mute')
classifierAction.addDocument('turn off sound', 'volume_mute')
classifierAction.addDocument('turn sound off', 'volume_mute')
classifierAction.addDocument('completely quiet', 'volume_mute')
classifierAction.addDocument('completely silent', 'volume_mute')
classifierAction.addDocument('no noise at all', 'volume_mute')
classifierAction.addDocument('no sound at all', 'volume_mute')
classifierAction.addDocument('mute device', 'volume_mute')
classifierAction.addDocument('stop all sound', 'volume_mute')
classifierAction.addDocument('turn off noises', 'volume_mute')
classifierAction.addDocument('stop all music', 'volume_mute')
classifierAction.addDocument('turn music off', 'volume_mute')
classifierAction.addDocument('no music', 'volume_mute')
classifierAction.addDocument('silence device', 'volume_mute')
classifierAction.addDocument('silence noise', 'volume_mute')
classifierAction.addDocument('silence music', 'volume_mute')
classifierAction.addDocument('silence', 'volume_mute')
classifierAction.addDocument('silence volume', 'volume_mute')
classifierAction.addDocument('silence media', 'volume_mute')
classifierAction.addDocument('make device mute', 'volume_mute')
classifierAction.addDocument('make device silent', 'volume_mute')
classifierAction.addDocument('mute media', 'volume_mute')
classifierAction.addDocument('mute all music', 'volume_mute')
classifierAction.addDocument('mute all sound', 'volume_mute')
classifierAction.addDocument('quit music', 'volume_mute')
classifierAction.addDocument('silence sound', 'volume_mute')
classifierAction.addDocument('no media sound', 'volume_mute')
classifierAction.addDocument('mute all sounds', 'volume_mute')
classifierAction.addDocument('kill the noise', 'volume_mute')
classifierAction.addDocument('kill the  sound', 'volume_mute')
classifierAction.addDocument('kill the music', 'volume_mute')
classifierAction.addDocument('mute all', 'volume_mute')
classifierAction.addDocument('no noise', 'volume_mute')
classifierAction.addDocument('no sound', 'volume_mute')
classifierAction.addDocument('no music', 'volume_mute')
classifierAction.addDocument('mute', 'volume_mute')
classifierAction.addDocument('silence', 'volume_mute')

// Check Device Classifiers
classifierAction.addDocument('what_devices', 'what_devices')
classifierAction.addDocument('what devices', 'what_devices')
classifierAction.addDocument('what can I do', 'what_devices')
classifierAction.addDocument('what can you do', 'what_devices')
classifierAction.addDocument('what can I control', 'what_devices')
classifierAction.addDocument('what can you control', 'what_devices')
classifierAction.addDocument('list of devices', 'what_devices')
classifierAction.addDocument('list of actions', 'what_devices')
classifierAction.addDocument('list of abilities', 'what_devices')
classifierAction.addDocument('what abilities', 'what_devices')
classifierAction.addDocument('list of controls', 'what_devices')
classifierAction.addDocument('all controlled devices', 'what_devices')
classifierAction.addDocument('tell me what you can do', 'what_devices')
classifierAction.addDocument('tell me all you can control', 'what_devices')
classifierAction.addDocument('all devices', 'what_devices')
classifierAction.addDocument('all abilities', 'what_devices')
classifierAction.addDocument('possible devices', 'what_devices')
classifierAction.addDocument('possible controls', 'what_devices')
classifierAction.addDocument('list of possible devices', 'what_devices')
classifierAction.addDocument('device', 'what_devices')
classifierAction.addDocument('devices', 'what_devices')

// Light Status Classifiers
classifierAction.addDocument('light_status', 'light_status')
classifierAction.addDocument('light status', 'light_status')
classifierAction.addDocument('are my lights on', 'light_status')
classifierAction.addDocument('check the lights', 'light_status')
classifierAction.addDocument('is my light on', 'light_status')
classifierAction.addDocument('check the lights', 'light_status')
classifierAction.addDocument('my light status', 'light_status')
classifierAction.addDocument('status of lights', 'light_status')
classifierAction.addDocument('what lights are on', 'light_status')
classifierAction.addDocument('is the light off', 'light_status')
classifierAction.addDocument('is my light off', 'light_status')
classifierAction.addDocument('are my lights off', 'light_status')
classifierAction.addDocument('light', 'light_status')
classifierAction.addDocument('lights', 'light_status')


// Switch Status Classifiers
classifierAction.addDocument('switch_status', 'switch_status')
classifierAction.addDocument('switch status', 'switch_status')
classifierAction.addDocument('are my switches on', 'switch_status')
classifierAction.addDocument('check the switch', 'switch_status')
classifierAction.addDocument('is my switch on', 'switch_status')
classifierAction.addDocument('is the switch on', 'switch_status')
classifierAction.addDocument('check the switch', 'switch_status')
classifierAction.addDocument('my switch status', 'switch_status')
classifierAction.addDocument('status of switch', 'switch_status')
classifierAction.addDocument('what switch is on', 'switch_status')


// Light Red Classifieres
classifierAction.addDocument('light_red', 'light_red')
classifierAction.addDocument('light red', 'light_red')
classifierAction.addDocument('turn light red', 'light_red')
classifierAction.addDocument('make light red', 'light_red')
classifierAction.addDocument('want light to be red', 'light_red')
classifierAction.addDocument('is light red', 'light_red')
classifierAction.addDocument('can be red', 'light_red')
classifierAction.addDocument('use red light', 'light_red')
classifierAction.addDocument('should be red', 'light_red')
classifierAction.addDocument('red', 'light_red')

// Light Green Classifieres
classifierAction.addDocument('light_green', 'light_green')
classifierAction.addDocument('light green', 'light_green')
classifierAction.addDocument('turn light green', 'light_green')
classifierAction.addDocument('make light green', 'light_green')
classifierAction.addDocument('want light to be green', 'light_green')
classifierAction.addDocument('should be green', 'light_green')
classifierAction.addDocument('is light green', 'light_green')
classifierAction.addDocument('can be green', 'light_green')
classifierAction.addDocument('use green light', 'light_green')
classifierAction.addDocument('green', 'light_green')

// Light Blue Classifieres
classifierAction.addDocument('light_blue', 'light_blue')
classifierAction.addDocument('light blue', 'light_blue')
classifierAction.addDocument('turn light blue', 'light_blue')
classifierAction.addDocument('make light blue', 'light_blue')
classifierAction.addDocument('want light to be blue', 'light_blue')
classifierAction.addDocument('should be blue', 'light_blue')
classifierAction.addDocument('is light blue', 'light_blue')
classifierAction.addDocument('can be blue', 'light_blue')
classifierAction.addDocument('use blue light', 'light_blue')
classifierAction.addDocument('blue', 'light_blue')


// Light White Classifiers
classifierAction.addDocument('light_white', 'light_white')
classifierAction.addDocument('light white', 'light_white')
classifierAction.addDocument('can be white', 'light_white')
classifierAction.addDocument('should be white', 'light_white')
classifierAction.addDocument('white', 'light_white')
classifierAction.addDocument('make white', 'light_white')
classifierAction.addDocument('turn white', 'light_white')
classifierAction.addDocument('use white light', 'light_white')


//Light Full Classifiers
classifierAction.addDocument('light_full', 'light_full')
classifierAction.addDocument('light full', 'light_full')
classifierAction.addDocument('full brightness', 'light_full')
classifierAction.addDocument('full light', 'light_full')
classifierAction.addDocument('light all the way up', 'light_full')
classifierAction.addDocument('light all the way', 'light_full')
classifierAction.addDocument('max light', 'light_full')
classifierAction.addDocument('maximum light', 'light_full')
classifierAction.addDocument('full', 'light_full')


//Light Medium Classifiers
classifierAction.addDocument('light_medium', 'light_medium')
classifierAction.addDocument('light medium', 'light_medium')
classifierAction.addDocument('medium brightness', 'light_medium')
classifierAction.addDocument('medium lights', 'light_medium')
classifierAction.addDocument('half brightness', 'light_medium')
classifierAction.addDocument('lights halfway', 'light_medium')
classifierAction.addDocument('light half', 'light_medium')
classifierAction.addDocument('medium', 'light_medium')


//Light Low Classifiers
classifierAction.addDocument('light_low', 'light_low')
classifierAction.addDocument('light low', 'light_low')
classifierAction.addDocument('low brightness', 'light_low')
classifierAction.addDocument('low lights', 'light_low')
classifierAction.addDocument('low', 'light_low')
classifierAction.addDocument('bring light low', 'light_low')

// Media Status Classifiers
classifierAction.addDocument('media_status', 'media_status')
classifierAction.addDocument('media status', 'media_status')
classifierAction.addDocument('is the media player on', 'media_status')
classifierAction.addDocument('check the media player', 'media_status')
classifierAction.addDocument('is media on', 'media_status')
classifierAction.addDocument('is the player on', 'media_status')
classifierAction.addDocument('check the player', 'media_status')
classifierAction.addDocument('my media status', 'media_status')
classifierAction.addDocument('status of media player', 'media_status')
classifierAction.addDocument('what media is on', 'media_status')
classifierAction.addDocument('is the media player off', 'media_status')
classifierAction.addDocument('is my player off', 'media_status')
classifierAction.addDocument('is the player on', 'media_status')
classifierAction.addDocument('is the player off', 'media_status')
classifierAction.addDocument('is my media player off', 'media_status')
classifierAction.addDocument('what is the status of the media', 'media_status')
classifierAction.addDocument('what is the status of the player', 'media_status')

// Media Play Classifiers
classifierAction.addDocument('media_play', 'media_play')
classifierAction.addDocument('media play', 'media_play')
classifierAction.addDocument('turn the media player on', 'media_play')
classifierAction.addDocument('turn on the media player', 'media_play')
classifierAction.addDocument('turn the player on', 'media_play')
classifierAction.addDocument("why isn't the the media player on?", 'media_play')
classifierAction.addDocument('media player should be on', 'media_play')
classifierAction.addDocument('player should be on', 'media_play')
classifierAction.addDocument('activate media', 'media_play')
classifierAction.addDocument('activate player', 'media_play')
classifierAction.addDocument('activate media player', 'media_play')
classifierAction.addDocument('turn player on', 'media_play')
classifierAction.addDocument('put on media player', 'media_play')
classifierAction.addDocument('start up media player', 'media_play')
classifierAction.addDocument('put on player', 'media_play')
classifierAction.addDocument('initiate media player', 'media_play')
classifierAction.addDocument('trigger media player on', 'media_play')
classifierAction.addDocument('start media player', 'media_play')
classifierAction.addDocument('turn media on', 'media_play')
classifierAction.addDocument('activate media', 'media_play')
classifierAction.addDocument('the media player should be on', 'media_play')
classifierAction.addDocument('start media', 'media_play')
classifierAction.addDocument('start media player should be on', 'media_play')
classifierAction.addDocument('start player', 'media_play')
classifierAction.addDocument('restart media', 'media_play')
classifierAction.addDocument('restart player', 'media_play')
classifierAction.addDocument('restart media player', 'media_play')
classifierAction.addDocument('start music', 'media_play')
classifierAction.addDocument('music player should be on', 'media_play')
classifierAction.addDocument('music on', 'media_play')
classifierAction.addDocument('media on', 'media_play')
classifierAction.addDocument('restart music', 'media_play')
classifierAction.addDocument('restart music player', 'media_play')
classifierAction.addDocument('restart music media player', 'media_play')
classifierAction.addDocument('play music', 'media_play')
classifierAction.addDocument('play media', 'media_play')
classifierAction.addDocument('play', 'media_play')
classifierAction.addDocument('start', 'media_play')

// Media Pause Classifiers
classifierAction.addDocument('media_pause', 'media_pause')
classifierAction.addDocument('media pause', 'media_pause')
classifierAction.addDocument('pause media', 'media_pause')
classifierAction.addDocument('pause player', 'media_pause')
classifierAction.addDocument('pause media player', 'media_pause')
classifierAction.addDocument('pause music', 'media_pause')
classifierAction.addDocument('pause', 'media_pause')

// Media Stop Classifiers
classifierAction.addDocument('media_stop', 'media_stop')
classifierAction.addDocument('media stop', 'media_stop')
classifierAction.addDocument('turn the media player off', 'media_stop')
classifierAction.addDocument('turn off the media player', 'media_stop')
classifierAction.addDocument('turn the player off', 'media_stop')
classifierAction.addDocument('why is the the media player on?', 'media_stop')
classifierAction.addDocument('media player should be off', 'media_stop')
classifierAction.addDocument('player should be off', 'media_stop')
classifierAction.addDocument('deactivate media', 'media_stop')
classifierAction.addDocument('deactivate player', 'media_stop')
classifierAction.addDocument('deactivate media player', 'media_stop')
classifierAction.addDocument('turn player off', 'media_stop')
classifierAction.addDocument('make player stop', 'media_stop')
classifierAction.addDocument('stop media player', 'media_stop')
classifierAction.addDocument('stop player', 'media_stop')
classifierAction.addDocument('turn media off', 'media_stop')
classifierAction.addDocument('deactivate media', 'media_stop')
classifierAction.addDocument('the media player should be off', 'media_stop')
classifierAction.addDocument('stop media', 'media_stop')
classifierAction.addDocument('media player should be off', 'media_stop')
classifierAction.addDocument('stop media', 'media_stop')
classifierAction.addDocument('stop music', 'media_stop')
classifierAction.addDocument('stop music player', 'media_stop')
classifierAction.addDocument('stop music media', 'media_stop')
classifierAction.addDocument('stop playing music', 'media_stop')
classifierAction.addDocument('stop playing media', 'media_stop')
classifierAction.addDocument('stop', 'media_stop')
classifierAction.addDocument('quit', 'media_stop')

// Climate Status Classifiers
classifierAction.addDocument('climate_status', 'climate_status')
classifierAction.addDocument('climate status', 'climate_status')
classifierAction.addDocument('what is the temperature', 'climate_status')
classifierAction.addDocument('current temperature', 'climate_status')
classifierAction.addDocument('temperature at home', 'climate_status')
classifierAction.addDocument('temperature in house', 'climate_status')
classifierAction.addDocument('check the temperature', 'climate_status')
classifierAction.addDocument('check the thermostat', 'climate_status')
classifierAction.addDocument('check the air conditioner', 'climate_status')
classifierAction.addDocument('check the AC', 'climate_status')
classifierAction.addDocument('check the ac', 'climate_status')
classifierAction.addDocument('check the A/C', 'climate_status')
classifierAction.addDocument('check the a/c', 'climate_status')
classifierAction.addDocument('check the heat', 'climate_status')
classifierAction.addDocument('is air conditioning working', 'climate_status')
classifierAction.addDocument('is air conditioning running', 'climate_status')
classifierAction.addDocument('is air conditioning on', 'climate_status')
classifierAction.addDocument('is heat working', 'climate_status')
classifierAction.addDocument('is heat on', 'climate_status')
classifierAction.addDocument('is heat running', 'climate_status')
classifierAction.addDocument('is thermostat working', 'climate_status')
classifierAction.addDocument('is thermostat running', 'climate_status')
classifierAction.addDocument('is thermostat set', 'climate_status')
classifierAction.addDocument('what does thermostat say', 'climate_status')
classifierAction.addDocument('how does thermostat read', 'climate_status')

// Temperature Up Classifiers
classifierAction.addDocument('temperature_up', 'temperature_up')
classifierAction.addDocument('temperature up', 'temperature_up')
classifierAction.addDocument('make warmer', 'temperature_up')
classifierAction.addDocument('make hotter', 'temperature_up')
classifierAction.addDocument('increase heat', 'temperature_up')
classifierAction.addDocument('turn heat up', 'temperature_up')
classifierAction.addDocument('turn air down', 'temperature_up')
classifierAction.addDocument('turn on heat', 'temperature_up')
classifierAction.addDocument('turn heat on', 'temperature_up')
classifierAction.addDocument('raise temperature', 'temperature_up')
classifierAction.addDocument('raise heat', 'temperature_up')
classifierAction.addDocument('up the heat', 'temperature_up')
classifierAction.addDocument('up the temperature', 'temperature_up')
classifierAction.addDocument('run the heat', 'temperature_up')
classifierAction.addDocument('turn up heat', 'temperature_up')
classifierAction.addDocument('turn up temperature', 'temperature_up')
classifierAction.addDocument('warmer', 'temperature_up')
classifierAction.addDocument('hotter', 'temperature_up')
classifierAction.addDocument('warm up', 'temperature_up')
classifierAction.addDocument('warming', 'temperature_up')
classifierAction.addDocument('heating', 'temperature_up')

// Temperature Down Classifiers
classifierAction.addDocument('temperature_down', 'temperature_down')
classifierAction.addDocument('temperature down', 'temperature_down')
classifierAction.addDocument('make cooler', 'temperature_down')
classifierAction.addDocument('make colder', 'temperature_down')
classifierAction.addDocument('increase air', 'temperature_down')
classifierAction.addDocument('turn air up', 'temperature_down')
classifierAction.addDocument('turn heat down', 'temperature_down')
classifierAction.addDocument('turn on air', 'temperature_down')
classifierAction.addDocument('turn air on', 'temperature_down')
classifierAction.addDocument('lower temperature', 'temperature_down')
classifierAction.addDocument('lower heat', 'temperature_down')
classifierAction.addDocument('up the air', 'temperature_down')
classifierAction.addDocument('lower the temperature', 'temperature_down')
classifierAction.addDocument('run the air', 'temperature_down')
classifierAction.addDocument('turn up air', 'temperature_down')
classifierAction.addDocument('turn up AC', 'temperature_down')
classifierAction.addDocument('turn up A/C', 'temperature_down')
classifierAction.addDocument('turn up ac', 'temperature_down')
classifierAction.addDocument('turn up a/c', 'temperature_down')
classifierAction.addDocument('turn down temperature', 'temperature_down')
classifierAction.addDocument('decrease temperature', 'temperature_down')
classifierAction.addDocument('turn on air conditioner', 'temperature_down')
classifierAction.addDocument('turn on AC', 'temperature_down')
classifierAction.addDocument('turn on A/C', 'temperature_down')
classifierAction.addDocument('turn on ac', 'temperature_down')
classifierAction.addDocument('turn on a/c', 'temperature_down')
classifierAction.addDocument('turn air on', 'temperature_down')
classifierAction.addDocument('turn A/C on', 'temperature_down')
classifierAction.addDocument('turn ac on', 'temperature_down')
classifierAction.addDocument('turn a/c on', 'temperature_down')
classifierAction.addDocument('turn air conditioner on', 'temperature_down')
classifierAction.addDocument('run the air conditioner', 'temperature_down')
classifierAction.addDocument('run the A/C', 'temperature_down')
classifierAction.addDocument('run the AC', 'temperature_down')
classifierAction.addDocument('run the ac', 'temperature_down')
classifierAction.addDocument('run the a/c', 'temperature_down')
classifierAction.addDocument('cooler', 'temperature_down')
classifierAction.addDocument('colder', 'temperature_down')

// Light Up Classifiers
classifierAction.addDocument('light_up', 'light_up')
classifierAction.addDocument('light up', 'light_up')
classifierAction.addDocument('make brighter', 'light_up')
classifierAction.addDocument('turn light up', 'light_up')
classifierAction.addDocument('raise lights', 'light_up')
classifierAction.addDocument('increase lights', 'light_up')
classifierAction.addDocument('increase brightness', 'light_up')
classifierAction.addDocument('up the light', 'light_up')
classifierAction.addDocument('raise brightness', 'light_up')
classifierAction.addDocument('brighter', 'light_up')
classifierAction.addDocument('lighter', 'light_up')
classifierAction.addDocument('stronger light', 'light_up')
classifierAction.addDocument('stronger', 'light_up')

// Light Down Classifiers
classifierAction.addDocument('light_down', 'light_down')
classifierAction.addDocument('light down', 'light_up')
classifierAction.addDocument('make darker', 'light_down')
classifierAction.addDocument('turn light down', 'light_down')
classifierAction.addDocument('lower lights', 'light_down')
classifierAction.addDocument('decrease lights', 'light_down')
classifierAction.addDocument('lower the lights', 'light_down')
classifierAction.addDocument('make dimmer', 'light_down')
classifierAction.addDocument('dim the lights', 'light_down')
classifierAction.addDocument('dim', 'light_down')
classifierAction.addDocument('dimmer', 'light_down')
classifierAction.addDocument('lower', 'light_down')
classifierAction.addDocument('darker', 'light_down')

//How Home Classifiers
classifierAction.addDocument('how_home', 'how_home')
classifierAction.addDocument('how home', 'how_home')
classifierAction.addDocument('how is my home doing', 'how_home')
classifierAction.addDocument('status of my home', 'how_home')
classifierAction.addDocument('status at home', 'how_home')


//What On Classifiers
classifierAction.addDocument('what_on', 'what_on')
classifierAction.addDocument('what on', 'what_on')
classifierAction.addDocument('whats on in my house', 'what_on')
classifierAction.addDocument('what devices are on', 'what_on')
classifierAction.addDocument('what is on at home', 'what_on')
classifierAction.addDocument('what device is on', 'what_on')
classifierAction.addDocument('whats turned on at home', 'what_on')

//What Off Classiferes
classifierAction.addDocument('what_off', 'what_off')
classifierAction.addDocument('what devices are off', 'what_off')
classifierAction.addDocument('are devices off', 'what_off')
classifierAction.addDocument('what is off', 'what_off')
classifierAction.addDocument('what is off in my house', 'what_off')

//What Lights Classifiers
classifierAction.addDocument('what_lights', 'what_lights')
classifierAction.addDocument('what lights', 'what_lights')

//What Switches Classifiers
classifierAction.addDocument('what_switches', 'what_switches')
classifierAction.addDocument('what switches', 'what switches')

//What Therm Classifiers
classifierAction.addDocument('what_therm', 'what_therm')
classifierAction.addDocument('what therm', 'what therm')

//What Media Classifers
classifierAction.addDocument('what_media', 'what_media')
classifierAction.addDocument('what media', 'what_media')




classifierAction.train()

// Turn the light on. (light_on)
//   Turn the light off. (light_off)
//   What lights are on? (light_status)
//   What all can you do for me? (what_devices)
//   Turn the air up. (temperature_up)
//   Turn the air down. (temperature_down)

classifierAction.save('classifierActionTest2.json', function (err, classifier) {
  if (err) {
    console.log(err)
  }
  // the classifier is saved to the classifier.json file!
})

// classifierAction.save('classifierAction.json', function (classifier) {
//   // the classifier is saved to the classifier.json file!
// })
